AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  # Primary New Account Notification S3 Solution Stack Set
  StackUpdate:
    Description: New Account Notification StackSet
    Type: String
    Default: AWS-Landing-Zone-CentralizedLoggingS3Primary
  SNSMsgJSON:
    Description: SNS Massage to Send
    Type: String
    Default: '{"policyNames":[{"type":"s3","region":"us-east-1","name":"cf-templates"}],"accountids":[]}'

Resources:
  # SNS Topic
  NewAccountNotificationSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: NewAccountNotification
      TopicName: account_lists
  # IAM Roles and Policies
  ReadOrgWriteSSMRole:
    Type:                          AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          Effect:                Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action:                'sts:AssumeRole'
      Path:                        /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName:                ReadOrganizationWriteSSM
          PolicyDocument:
            Statement:
              - Effect:                Allow
                Action:
                  - SNS:Publish
                Resource:              "*"
              - Effect:                Allow
                Action:
                  - cloudformation:DescribeStackSet
                  - cloudformation:UpdateStackSet
                  - cloudformation:DescribeChangeSet
                  - cloudformation:ListChangeSets
                  - cloudformation:DescribeStacks
                Resource:              "*"
              - Effect:                Allow
                Action:
                  - organizations:ListAccounts
                Resource:              "*"
              - Effect:                Allow
                Action:
                  - 'ssm:GetParameter*'
                  - 'ssm:PutParameter'
                Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/org/member/accounts'
  NewAccountNotification:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: When a new account is created it will send a json message to an sns topic.
      Handler: new_account_notification.lambda_handler
      FunctionName: new_account_notification
      Runtime: python3.7
      Timeout: 360
      CodeUri:
         Bucket: !Sub "${AWS::AccountId}-${AWS::Region}-code"
         Key: 'new_account_notification.zip'
      Environment:
        Variables:
          StackSettoUpdate: !Ref "StackUpdate"
          SNStopicArn: !Ref NewAccountNotificationSNSTopic
          SNSMessageTemplate: !Ref "SNSMsgJSON"
      Events:
        NewOrgAccountEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail:
                eventSource:
                  - organizations.amazonaws.com
                eventName:
                  - CreateAccount
              source:
                - "aws.organizations"
              detail-type:
                - "AWS API Call via CloudTrail"
      Policies:
        - AWSLambdaExecute # Managed Policy
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect:                Allow
              Action:
                - SNS:Publish
              Resource:              "*"
            - Effect:                Allow
              Action:
                - cloudformation:DescribeStackSet
                - cloudformation:UpdateStackSet
                - cloudformation:DescribeChangeSet
                - cloudformation:ListChangeSets
                - cloudformation:DescribeStacks
              Resource:              "*"
            - Effect:                Allow
              Action:
                - organizations:ListAccounts
              Resource:              "*"
            - Effect:                Allow
              Action:
                - 'ssm:GetParameter*'
                - 'ssm:PutParameter'
              Resource: !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/org/member/accounts'
